Added some inspectable to work with arrow direction, background color…
azurechen/ACTabScrollView pull request #13
Opened 2017-04-30 13:52 UTC by htarwara6245

Added New Inspectable

- Arrow Direction (Upside or down)
- Arrow Background Color
- Arrow Width
- Arrow Height

2017-05-02 08:12 UTC, azurechen requested changes
Please reset the following files. These files shouldn't be changed in this commit.
```
.DS_Store
ACTabScrollView.xcodeproj/project.pbxproj
ACTabScrollView/Base.lproj/Main.storyboard
ACTabScrollView/Info.plist
```

2017-05-02 08:12 UTC, azurechen commented on Sources/ACTabScrollView.swift
> +        if upsideArrowDirection{
according to the swift guideline, there should be one more space between upsideArrowDirection and {

2017-05-02 08:12 UTC, azurechen commented on Sources/ACTabScrollView.swift
> +        }else{
same issue

2017-05-02 08:12 UTC, azurechen commented on Sources/ACTabScrollView.swift
> +
remove the unnecessary newline

2017-05-02 08:12 UTC, azurechen commented on Sources/ACTabScrollView.swift
> +        }
```
ctx.beginPath()

if upsideArrowDirection! {
    ctx.move(to: CGPoint(x: 0, y: 1))
    ctx.addQuadCurve(to: CGPoint(x: maxX * 0.2 , y: maxY * 0.8), control: CGPoint(x: maxX * 0.12, y: 1))
    ctx.addLine(to: CGPoint(x: midX - maxX * 0.05, y: maxY * 0.1))
    ctx.addQuadCurve(to: CGPoint(x: midX + maxX * 0.05, y: maxY * 0.1), control: CGPoint(x: midX, y: maxY))
    ctx.addLine(to: CGPoint(x: maxX * 0.8, y: maxY * 0.8))
    ctx.addQuadCurve(to: CGPoint(x: maxX, y: 1), control: CGPoint(x: maxX * 0.88, y: 0))
} else {
    ctx.move(to: CGPoint(x: 0, y: 0))
    ctx.addQuadCurve(to: CGPoint(x: maxX * 0.2 , y: maxY * 0.2), control: CGPoint(x: maxX * 0.12, y: 0))
    ctx.addLine(to: CGPoint(x: midX - maxX * 0.05, y: maxY * 0.9))
    ctx.addQuadCurve(to: CGPoint(x: midX + maxX * 0.05, y: maxY * 0.9), control: CGPoint(x: midX, y: maxY))
    ctx.addLine(to: CGPoint(x: maxX * 0.8, y: maxY * 0.2))
    ctx.addQuadCurve(to: CGPoint(x: maxX, y: 0), control: CGPoint(x: maxX * 0.88, y: 0))
}

ctx.closePath()
ctx.setFillColor((arrorBackgroundColor?.cgColor)!)
ctx.fillPath();
```

2017-05-02 08:12 UTC, azurechen commented on Sources/ACTabScrollView.swift
> +    @IBInspectable open var upsideArrowDirection : Bool = true
please set default false for the demo at readme file.

2017-05-08 16:31 UTC, closed without merging

2017-05-08 16:31 UTC, htarwara6245 commented on Sources/ACTabScrollView.swift
> +        }
Close this pull request now cause I am having trouble marge and conflict issue